### ISSUE TITLE
SonarQube analysis failing on Master branch

### ISSUE THREAD

**Issue by m-g-sonar** [MazarineBlue/MazarineBlue#48]
Hey,

A small message to warn you that your SonarQube analysis is currently failing on your `master branch`, because of the `sonar.tests` property set in your parent POM. I don't know which branch you are (or were) following for regular analysis, but no new analysis has been performed with your last commit: [MazarineBlue on SonarQube.com](https://sonarqube.com/dashboard?id=org.mazarineblue%3AMazarineBlue)

Module `Utilities` (master branch) does not have any test folder, but inherit the property from its parent POM. Consequently, SonarQube analysis will fail, explicitly. Note that your `develop` branch is unaffected, as tests are present there.

Best regards,
Michael
_SonarQube SonarJava Analyzer team_

**Comment by akruijff** [comment]
Thanks for you message. I have a local script to invoke SonarQube analysis.

The utilities module contains code intended to be reused by other modules. In this case it contains code that is covered by tests in other modules. Currently, the utilities module contains code so trivial that there is very little risk. This issue will be resolved when more code is introduced.
